version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/ecommerce
    ports:
      - 8000:8000
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

