# Generated by Django 3.1.6 on 2021-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationvalue',
            name='value',
            field=models.CharField(max_length=400, verbose_name='Значение характеристики'),
        ),
    ]
