# Generated by Django 3.1.6 on 2021-03-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_returnitem_returnletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='comment',
        ),
        migrations.AddField(
            model_name='returnletter',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
