# Generated by Django 3.1.6 on 2021-03-13 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210313_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество товара'),
        ),
    ]
