# Generated by Django 3.1.6 on 2021-03-13 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210313_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Общая стоимость товара'),
        ),
    ]
