# Generated by Django 3.1.6 on 2021-03-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210313_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='morga',
            field=models.PositiveIntegerField(default=25, verbose_name='Моржа в %'),
        ),
        migrations.AddField(
            model_name='product',
            name='true_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена на товар без моржы'),
            preserve_default=False,
        ),
    ]
