# Generated by Django 3.2 on 2021-05-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210518_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена на товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='true_price',
            field=models.IntegerField(verbose_name='Цена на товар без наценки'),
        ),
    ]
