# Generated by Django 3.2 on 2021-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210519_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.PositiveIntegerField(null=True, verbose_name='Маржа в %'),
        ),
    ]
