# Generated by Django 3.2 on 2021-05-27 11:28

from django.db import migrations

def gen_margin(apps, schema_editor):
    Product = apps.get_model('mainapp', 'Product')
    for product in Product.objects.all():
        product.margin = round(((product.price - product.true_price) / product.price) * 100)
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_product_margin'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_margin, reverse_code=migrations.RunPython.noop),
    ]
