# Generated by Django 3.2 on 2021-05-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_populate_margin_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='margin',
            field=models.PositiveIntegerField(verbose_name='Маржа в %'),
        ),
    ]
