# Generated by Django 3.2 on 2021-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_margin_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка в %'),
        ),
    ]
