# Generated by Django 3.2 on 2021-05-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_before_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена на товар до скидки'),
        ),
    ]
