# Generated by Django 3.1.6 on 2021-03-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210303_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='device_id',
        ),
    ]
