# Generated by Django 3.1.6 on 2021-03-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('region', models.CharField(max_length=100, verbose_name='Область')),
                ('locality', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('post_office', models.CharField(max_length=200, verbose_name='Отделение новой почты')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_processing', 'В обработке'), ('delivered', 'Доставлен'), ('completed', 'Завершен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Корзина')),
            ],
        ),
    ]
