# Generated by Django 3.1.6 on 2021-03-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('liqpay', 'Приват 24, картой VISA / MASTERCARD (LiqPay)')], default='liqpay', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
