# Generated by Django 3.2 on 2021-05-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20210318_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-cart__id'], 'verbose_name': 'Продукт корзины', 'verbose_name_plural': 'Продукты корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Общая стоимость корзины'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Общая стоимость товара'),
        ),
    ]
