# Generated by Django 3.2 on 2021-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20210519_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TTN',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ТТН №'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=10000, verbose_name='№'),
        ),
    ]
