# Generated by Django 3.2 on 2021-05-22 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210522_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TTN',
            field=models.CharField(default='00000000000000', max_length=100, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)], verbose_name='ТТН №'),
        ),
    ]
