# Generated by Django 3.2 on 2021-05-22 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_order_ttn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TTN',
            field=models.CharField(default='00000000000000', max_length=100, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)], verbose_name='ТТН №'),
        ),
    ]
