# Generated by Django 3.2 on 2021-05-26 13:46

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    for row in Cart.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_cart_uuid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
